version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: gerenciador_membros_db
    environment:
      POSTGRES_DB: gerenciador_de_membros
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1995
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gerenciador_network

volumes:
  postgres_data:

networks:
  gerenciador_network: